// Global variables
let currentMaterial = '';
let aiSummary = '';
let quizQuestions = [];
let currentQuestionIndex = 0;
let userScore = 0;
let timer;
let timeLeft = 20;
let userAnswers = [];

// Simple AI function - NO API NEEDED
function generateSummary() {
    const materialInput = document.getElementById('material-input');
    
    if (!materialInput) {
        alert('Error: Input element tidak ditemukan!');
        return;
    }
    
    const materialText = materialInput.value.trim();
    
    if (materialText.length < 10) {
        alert('Masukkan minimal 10 karakter materi.');
        return;
    }
    
    currentMaterial = materialText;
    
    // Show loading
    const btn = document.getElementById('generate-btn');
    if (!btn) {
        alert('Error: Button tidak ditemukan!');
        return;
    }
    
    btn.disabled = true;
    btn.innerHTML = '<div class="loading-spinner"></div> Memproses...';
    
    // Simulate AI processing (2 seconds)
    setTimeout(() => {
        // Create smart summary
        aiSummary = createSmartSummary(materialText);
        
        // Display results
        const originalElem = document.getElementById('original-material');
        const summaryElem = document.getElementById('ai-summary');
        const resultsSection = document.getElementById('results-section');
        
        if (originalElem && summaryElem && resultsSection) {
            originalElem.textContent = currentMaterial;
            summaryElem.textContent = aiSummary;
            resultsSection.style.display = 'block';
            
            // Scroll to results
            resultsSection.scrollIntoView({ behavior: 'smooth' });
        } else {
            alert('Error: Element results tidak ditemukan!');
        }
        
        // Reset button
        btn.disabled = false;
        btn.innerHTML = 'Summarize';
        
    }, 2000);
}

// Smart summary algorithm
function createSmartSummary(text) {
    const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 10);
    const words = text.toLowerCase().split(/\s+/);
    
    // Extract important words
    const importantWords = [];
    words.forEach(word => {
        if (word.length > 4 && !['yang', 'dengan', 'dalam', 'adalah', 'untuk', 'dari', 'pada'].includes(word)) {
            importantWords.push(word);
        }
    });
    
    let summary = "🤖 RINGKASAN AI\n\n";
    summary += "🎯 POIN-POIN PENTING:\n\n";
    
    // Take important sentences
    if (sentences.length >= 3) {
        summary += `• ${sentences[0].trim()}\n\n`;
        summary += `• ${sentences[Math.floor(sentences.length/2)].trim()}\n\n`;
        summary += `• ${sentences[sentences.length-1].trim()}\n\n`;
    } else {
        sentences.forEach(sentence => {
            summary += `• ${sentence.trim()}\n\n`;
        });
    }
    
    summary += "💡 TIPS BELAJAR:\n";
    summary += "• Fokus pada konsep utama\n";
    summary += "• Buat catatan singkat\n";
    summary += "• Review secara berkala\n\n";
    summary += "✨ Generated by Smart AI Algorithm";
    
    return summary;
}

// Start quiz function
function startQuiz() {
    if (!currentMaterial) {
        alert('Buat rangkuman terlebih dahulu!');
        return;
    }
    
    // Use predefined questions
    quizQuestions = [
        {
            question: "Apa ide utama dari materi ini?",
            options: ["A. Konsep dasar", "B. Detail teknis", "C. Contoh aplikasi", "D. Semua benar"],
            correctAnswer: "A"
        },
        {
            question: "Manakah yang merupakan poin penting?",
            options: ["A. Semua informasi", "B. Konsep utama", "C. Contoh spesifik", "D. Data pendukung"],
            correctAnswer: "B"
        },
        {
            question: "Bagaimana cara terbaik memahami materi ini?",
            options: [
                "A. Menghafal semua isi",
                "B. Memahami konsep dan berlatih", 
                "C. Membaca sekali saja",
                "D. Mencari materi lain"
            ],
            correctAnswer: "B"
        }
    ];
    
    const resultsSection = document.getElementById('results-section');
    const quizSection = document.getElementById('quiz-section');
    
    if (resultsSection && quizSection) {
        resultsSection.style.display = 'none';
        quizSection.style.display = 'block';
        
        currentQuestionIndex = 0;
        userScore = 0;
        userAnswers = [];
        showQuestion();
    }
}

// Show question
function showQuestion() {
    if (currentQuestionIndex >= quizQuestions.length) {
        showResults();
        return;
    }
    
    const question = quizQuestions[currentQuestionIndex];
    const questionCounter = document.getElementById('question-counter');
    const questionText = document.getElementById('question-text');
    const optionsContainer = document.getElementById('options-container');
    const nextBtn = document.getElementById('next-btn');
    
    if (questionCounter) questionCounter.textContent = `Soal ${currentQuestionIndex + 1}/${quizQuestions.length}`;
    if (questionText) questionText.textContent = question.question;
    
    if (optionsContainer) {
        optionsContainer.innerHTML = '';
        question.options.forEach(option => {
            const btn = document.createElement('button');
            btn.className = 'option-btn';
            btn.textContent = option;
            btn.onclick = () => selectOption(btn, option);
            optionsContainer.appendChild(btn);
        });
    }
    
    if (nextBtn) nextBtn.style.display = 'none';
    startTimer();
}

// Timer functions
function startTimer() {
    timeLeft = 20;
    updateTimer();
    
    clearInterval(timer);
    timer = setInterval(() => {
        timeLeft--;
        updateTimer();
        
        if (timeLeft <= 0) {
            clearInterval(timer);
            handleTimeUp();
        }
    }, 1000);
}

function updateTimer() {
    const timerElement = document.getElementById('timer');
    if (timerElement) {
        const timerText = timerElement.querySelector('.timer-text');
        if (timerText) {
            timerText.textContent = `${timeLeft}s`;
            
            if (timeLeft <= 5) {
                timerElement.style.background = '#ef4444';
            } else if (timeLeft <= 10) {
                timerElement.style.background = '#f59e0b';
            } else {
                timerElement.style.background = '#4f46e5';
            }
        }
    }
}

function handleTimeUp() {
    const question = quizQuestions[currentQuestionIndex];
    const options = document.querySelectorAll('.option-btn');
    
    options.forEach(btn => {
        if (btn.textContent.startsWith(question.correctAnswer)) {
            btn.classList.add('correct');
        }
    });
    
    userAnswers.push({
        question: question.question,
        userAnswer: 'Timeout',
        correctAnswer: question.correctAnswer,
        isCorrect: false
    });
    
    const nextBtn = document.getElementById('next-btn');
    if (nextBtn) nextBtn.style.display = 'block';
}

function selectOption(selectedBtn, selectedOption) {
    const allOptions = document.querySelectorAll('.option-btn');
    allOptions.forEach(btn => {
        btn.classList.remove('selected');
        btn.onclick = null;
    });
    
    selectedBtn.classList.add('selected');
    clearInterval(timer);
    
    const question = quizQuestions[currentQuestionIndex];
    const isCorrect = selectedOption.startsWith(question.correctAnswer);
    
    // Show correct/incorrect
    allOptions.forEach(btn => {
        if (btn.textContent.startsWith(question.correctAnswer)) {
            btn.classList.add('correct');
        } else if (btn === selectedBtn && !isCorrect) {
            btn.classList.add('incorrect');
        }
    });
    
    if (isCorrect) userScore++;
    
    userAnswers.push({
        question: question.question,
        userAnswer: selectedOption,
        correctAnswer: question.correctAnswer,
        isCorrect: isCorrect
    });
    
    const nextBtn = document.getElementById('next-btn');
    if (nextBtn) nextBtn.style.display = 'block';
}

function nextQuestion() {
    currentQuestionIndex++;
    showQuestion();
}

// Show results
function showResults() {
    const quizSection = document.getElementById('quiz-section');
    const finalResults = document.getElementById('final-results');
    
    if (quizSection && finalResults) {
        quizSection.style.display = 'none';
        finalResults.style.display = 'block';
        
        const scorePercent = Math.round((userScore / quizQuestions.length) * 100);
        const scoreElement = document.getElementById('score-percent');
        const descElement = document.getElementById('score-description');
        const circle = document.querySelector('.score-circle');
        
        // Animate score
        if (scoreElement) {
            let current = 0;
            const interval = setInterval(() => {
                if (current >= scorePercent) {
                    clearInterval(interval);
                    scoreElement.textContent = scorePercent + '%';
                } else {
                    current++;
                    scoreElement.textContent = current + '%';
                }
            }, 20);
        }
        
        // Update description
        if (descElement) {
            if (scorePercent >= 80) descElement.textContent = 'Excellent!';
            else if (scorePercent >= 60) descElement.textContent = 'Good job!';
            else descElement.textContent = 'Keep practicing!';
        }
        
        // Update circle
        if (circle) {
            circle.style.background = `conic-gradient(#10b981 ${scorePercent}%, #e5e7eb ${scorePercent}%)`;
        }
        
        generateQuizContent();
    }
}

function generateQuizContent() {
    let content = '';
    userAnswers.forEach((answer, index) => {
        content += `Soal ${index + 1}: ${answer.question}\n`;
        content += `Jawaban Anda: ${answer.userAnswer}\n`;
        content += `Jawaban Benar: ${answer.correctAnswer}\n`;
        content += `Status: ${answer.isCorrect ? 'Benar' : 'Salah'}\n\n`;
    });
    
    const copyQuizContent = document.getElementById('copy-quiz-content');
    if (copyQuizContent) {
        copyQuizContent.textContent = content;
    }
}

function copyQuiz() {
    const content = document.getElementById('copy-quiz-content');
    if (content) {
        copyToClipboard(content.textContent);
        alert('Kuis disalin!');
    }
}

// Copy functions
function copyOriginalMaterial() {
    copyToClipboard(currentMaterial);
    alert('Materi asli disalin!');
}

function copySummary() {
    copyToClipboard(aiSummary);
    alert('Rangkuman disalin!');
}

function copyToClipboard(text) {
    navigator.clipboard.writeText(text).then(() => {
        console.log('Text copied to clipboard');
    }).catch(err => {
        // Fallback untuk browser lama
        const textarea = document.createElement('textarea');
        textarea.value = text;
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand('copy');
        document.body.removeChild(textarea);
    });
}

// Tab switching function
function switchTab(tabName) {
    // Hide all tab contents
    document.querySelectorAll('.tab-content').forEach(tab => {
        tab.classList.remove('active');
    });
    
    // Remove active class from all buttons
    document.querySelectorAll('.tab-btn').forEach(btn => {
        btn.classList.remove('active');
    });
    
    // Show selected tab
    const selectedTab = document.getElementById(`${tabName}-tab`);
    if (selectedTab) {
        selectedTab.classList.add('active');
    }
    
    // Activate selected button
    if (event && event.target) {
        event.target.classList.add('active');
    }
}

// File upload handling
document.addEventListener('DOMContentLoaded', function() {
    console.log('Website loaded successfully!');
    
    const uploadArea = document.getElementById('upload-area');
    const fileInput = document.getElementById('file-input');
    
    if (uploadArea) {
        uploadArea.addEventListener('dragover', function(e) {
            e.preventDefault();
            uploadArea.classList.add('drag-over');
        });
        
        uploadArea.addEventListener('dragleave', function() {
            uploadArea.classList.remove('drag-over');
        });
        
        uploadArea.addEventListener('drop', function(e) {
            e.preventDefault();
            uploadArea.classList.remove('drag-over');
            const files = e.dataTransfer.files;
            if (files.length > 0) {
                handleFileUpload(files[0]);
            }
        });
        
        // Click to upload
        uploadArea.addEventListener('click', function() {
            fileInput.click();
        });
    }
    
    if (fileInput) {
        fileInput.addEventListener('change', function(e) {
            if (e.target.files.length > 0) {
                handleFileUpload(e.target.files[0]);
            }
        });
    }
});

function handleFileUpload(file) {
    if (file.type === 'text/plain' || file.name.toLowerCase().endsWith('.txt')) {
        const reader = new FileReader();
        reader.onload = function(e) {
            currentMaterial = e.target.result;
            const materialInput = document.getElementById('material-input');
            if (materialInput) {
                materialInput.value = currentMaterial;
            }
            switchTab('text');
        };
        reader.readAsText(file);
    } else {
        alert('Hanya file teks (.txt) yang didukung untuk saat ini.');
    }
}

// Navigation functions
function backToSummary() {
    const finalResults = document.getElementById('final-results');
    const resultsSection = document.getElementById('results-section');
    
    if (finalResults && resultsSection) {
        finalResults.style.display = 'none';
        resultsSection.style.display = 'block';
    }
}

function backToHome() {
    const finalResults = document.getElementById('final-results');
    const resultsSection = document.getElementById('results-section');
    const quizSection = document.getElementById('quiz-section');
    
    if (finalResults) finalResults.style.display = 'none';
    if (resultsSection) resultsSection.style.display = 'none';
    if (quizSection) quizSection.style.display = 'none';
    
    window.scrollTo(0, 0);
}

// Initialize
console.log('CompAInion initialized!');
